### ISSUE TITLE
Hello World C host works on M1 macOS but fails on x86

### ISSUE THREAD

**Issue by rtfeldman** [roc-lang/roc#3326]
As of 8e7943eaca0041f5b0a8c770ce2fabeea89e00d9, the hello world C host fails to build on x86 Mac (running Monterey v12.4), but works on an M1 Mac. Here's the output:
```
$ cargo run examples/hello-world/main.roc
🔨 Rebuilding host...
thread '<unnamed>' panicked at 'Failed to rebuild host.c - stderr of the `clang` command was:
/Users/rtfeldman/Downloads/roc_nightly-macos_x86_64-a37226-2022-06-25/examples/hello-world/c-platform/host.c:1:10: fatal error: 'errno.h' file not found
#include <errno.h>
         ^~~~~~~~~
1 error generated.
', compiler/build/src/link.rs:1189:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', cli/src/build.rs:268:46
```

It works fine when changing to the Rust host.
